### ISSUE TITLE
Version dependencv

### ISSUE THREAD

**Issue by smoeding** [oxc/puppet-dovecot#16]

**Comment by smoeding** [comment]
The version dependencies for stdlib and concat state less than 5.0.0 for both modules.
Currently both modules are available at a 5.x.y major release.

**Comment by oxc** [comment]
Yes, that's what I wanted to fix before publishing a release for #15. I'll do that as soon as possible.

**Comment by oxc** [comment]
Released in [v2.1.0](https://github.com/oxc/puppet-dovecot/releases/tag/v2.1.0)

**Comment by smoeding** [comment]
Thanks for the quick response!
