### ISSUE TITLE
notation for empty section

### ISSUE THREAD

**Issue by leitmedium** [oxc/puppet-dovecot#18]
Hey,

I am having a hard time finding a way to declare an empty section, like

```
plugin {
}
```

This notiation…

```
plugin        => {},
```

… gets ignored unless you put configuration entries in the brackets.

Do you have a suggestion on how to write the puppet code?

Thanks and best.

**Comment by oxc** [comment]
Interesting corner case. Can you explain why this is needed?

**Comment by oxc** [comment]
@leitmedium, can you give any insight on this?

**Comment by oxc** [comment]
Closing this due to lack of feedback.
