### ISSUE TITLE
Purging config files under conf.d

### ISSUE THREAD

**Issue by mat1010** [oxc/puppet-dovecot#21]
Unmanaged configs within `/etc/dovecot` are being wiped out already by
https://github.com/oxc/puppet-dovecot/blob/855c0d85bd206eafeb339b2d073c55e6dbe5d77f/manifests/configuration.pp#L4-L12
Is there anything that would speak against adding the same purge mechanism to the underlying `conf.d` directory? Right now the `conf.d` is left untouched if there are already untouched example configs (like it's the case for e.g. EL7):
https://github.com/oxc/puppet-dovecot/blob/855c0d85bd206eafeb339b2d073c55e6dbe5d77f/manifests/configuration.pp#L15-L17

**Comment by oxc** [comment]
Are you sure about that? I thought the recurse=>true would purge the conf.d directory as well, but perhaps it does not recurse into managed directories.
Would you provide a pull request for that change?
