### ISSUE TITLE
Stdlib dependency outdated

### ISSUE THREAD

**Issue by mat1010** [oxc/puppet-dovecot#24]
The current stdlib requirement of < 6.0.0 is outdated due to the latest [stdlib](https://forge.puppet.com/puppetlabs/stdlib) releases which are > 6.0.0. The requirement of stdlib should be bumped to < 7.0.0 to avoid issues during installing / upgrading the module itself.

**Comment by mat1010** [comment]
@oxc Have you had a chance to look into this? We are running the module since several weeks with the latest [puppet-stdlib](https://forge.puppet.com/puppetlabs/stdlib) version

**Comment by oxc** [comment]
I'm sorry, I somehow lost track of this issue. I'll handle it ASAP, presumably in the next two days.

**Comment by oxc** [comment]
Released in [v3.1.0](https://forge.puppet.com/oxc/dovecot/3.1.0/)

Sorry again for the delay.
