### ISSUE TITLE
Multiple passdb configs in 10-auth

### ISSUE THREAD

**Issue by shneeba** [oxc/puppet-dovecot#27]
Hi there,

I'm trying to implement multiple passdb's in my 10-auth config as users need to authenticate against two domains, however I don't seem to see a way to do this.

I can define the LDAP config within the .ext files however defining multiple passdb's isn't possible due to using duplicate key values.

```
      '10-auth'    => {
        disable_plaintext_auth => 'yes',
        auth_default_realm     => 'domain.co.uk',
        auth_username_char     => 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ01234567890.-_@\'',
        auth_mechanisms        => 'plain login',
        passdb                 => {
          driver => 'ldap',
          args   => '/etc/dovecot/dovecot-pass-method1-ldap.conf.ext',
        },
        passdb                 => {
          driver => 'ldap',
          args   => '/etc/dovecot/dovecot-pass-method2-ldap.conf.ext',
        },
        userdb                 => {
          driver => 'ldap',
          args   => '/etc/dovecot/dovecot-user-method1-ldap.conf.ext',
        },
        userdb                 => {
          driver => 'ldap',
          args   => '/etc/dovecot/dovecot-user-method2-ldap.conf.ext',
        },
      },
```

I can't work out a way that this could be done, I was thinking of using an !include configuration but this isn't supported with the whole key value pair setup.

Has anyone been able to setup dual authentication using this module?

Cheers.

**Comment by oxc** [comment]
You're right, this seems not to be supported by the module. You could try putting the passdb entries into consecutive config files (e.g. `10-auth-passdb01`, `10-auth-passdb02`), though I'm not a 100% sure if dovecot supports that.

**Comment by shneeba** [comment]
Arghh why didn't I think of that!!

Yes that works, dovecot is showing me the correct config with `dovecot -n` after doing a puppet run.

Such a simple workaround, thanks for the nudge in the right direction. For anyone else that wants to do this, I've configured it like so:

```
      '10-auth'    => {
        disable_plaintext_auth => 'yes',
        auth_default_realm     => 'domain.co.uk',
        auth_username_chars    => 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ01234567890.-_@\'',
        auth_mechanisms        => 'plain login',
        passdb                 => {
          driver => 'ldap',
          args   => '/etc/dovecot/dovecot-pass-method1-ldap.conf.ext',
        },
        userdb                 => {
          driver => 'ldap',
          args   => '/etc/dovecot/dovecot-user-method1-ldap.conf.ext',
        },
      },
      '10-auth02'  => {
        passdb => {
          driver => 'ldap',
          args   => '/etc/dovecot/dovecot-pass-method2-ldap.conf.ext',
        },
        userdb => {
          driver => 'ldap',
          args   => '/etc/dovecot/dovecot-user-method2-ldap.conf.ext',
        },
      },
```

Thanks again for such a quick response and handy module.

**Comment by oxc** [comment]
Great! Glad to help :)

Since supporting this in the module would require incompatible changes, I will close this one until someone finds a use-case that cannot be easily worked around.
